upgraded to kubernetes 1.12.1 (and the new kubeadm config format)
- the new kubeadm configuration format uses different sub-configurations
  (https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3)
  - InitConfiguration: needed by masters at 'kubeadm init'
  - ClusterConfiguration: cluster-wide configuration
  - JoinConfiguration: describes a particular node (running a kubelet)

diff --git a/hakubeinstaller/templates/master.sh.j2 b/hakubeinstaller/templates/master.sh.j2
--- a/hakubeinstaller/templates/master.sh.j2
+++ b/hakubeinstaller/templates/master.sh.j2
@@ -172,99 +172,19 @@ retrying_scp root@{{ cluster["masters"][0]["privateIP"] }} /etc/kubernetes/pki/f
 #
 # Run kubeadm
 #
-cat > kubeadm-config.yaml <<EOL
-apiVersion: kubeadm.k8s.io/v1alpha2
-kind: MasterConfiguration
-kubernetesVersion: v{{ cluster["kubernetesVersion"] }}
-bootstrapTokens:
-- groups:
-  - system:bootstrappers:kubeadm:default-node-token
-  token: {{ cluster_token }}
-  # Never expire token
-  ttl: 0s
-api:
-  # Sets a stable IP address or DNS name for the control plane endpoint; it
-  # can be a valid IP address or a RFC-1123 DNS subdomain, both with
-  # optional TCP port.
-  # In a cluster with more than one control plane instances, this field
-  # should be assigned the address of the external load balancer in front
-  # of the control plane instances.
-  # This endpoint will be used by pods in the kube-proxy daemonset to connect
-  # to the apiserver. It is written by kubeadm to a generated kube-proxy
-  # configmap. It will also be written to the kubeadm-generated kubeconfig.
-  controlPlaneEndpoint: "{{ cluster["masterLoadBalancerAddress"] }}:6443"
-
-  # Each apiserver advertises itself as a separate k8s endpoint. This needs
-  # to be combined with using the lease-based endpoint-reconciler, which
-  # should be enabled in the apiserver by default.
-  advertiseAddress: "{{ master["privateIP"] }}"
-  bindPort: 6443
-
-clusterName: {{ cluster["clusterName"] }}
-certificatesDir: /etc/kubernetes/pki
-etcd:
-  external:
-    endpoints:
-    # only connect to local etcd server
-    - {{ "https://%s:2379" | format(master["privateIP"]) }}
-    caFile: /etc/kubernetes/pki/etcd/ca.pem
-    certFile: /etc/kubernetes/pki/etcd/client.pem
-    keyFile: /etc/kubernetes/pki/etcd/client-key.pem
-imageRepository: k8s.gcr.io
-kubeProxy:
-  config:
-kubeletConfiguration:
-  baseConfig:
-apiServerCertSANs:
-- 127.0.0.1
-- {{ master["privateIP"] }}
-- {{ cluster["masterLoadBalancerAddress"] }}
-{% for master_fqdn in cluster["masterFQDNs"] %}
-- {{ master_fqdn }}
-{% endfor %}
-networking:
-  dnsDomain: cluster.local
-  podSubnet: 10.32.0.0/12
-  serviceSubnet: 10.96.0.0/12
-# TODO: according to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#new-deprecations
-#       we should make use of out-of-tree cloud providers, but it is not
-#       clear from the docs how to achieve this. As a temporary workaround,
-#       we make use of legacy in-tree cloud providers (via arguments to the
-#       apiserver and controller-manager)
-apiServerExtraArgs:
-{% if cluster["hooks"].get("cloudProvider") %}
-  cloud-provider: "{{ cluster["hooks"]["cloudProvider"] }}"
-{% endif %}
-{% if cluster["hooks"].get("cloudProviderConfig") %}
-  cloud-config: "/etc/kubernetes/cloud-config.json"
-apiServerExtraVolumes:
-- name: cloud
-  hostPath: "/etc/kubernetes/cloud-config.json"
-  mountPath: "/etc/kubernetes/cloud-config.json"
-{% endif %}
-controllerManagerExtraArgs:
-  # required if we want prometheus to be able to scrape (default: 127.0.0.1)
-  address: 0.0.0.0
-{% if cluster["hooks"].get("cloudProvider") %}
-  cloud-provider: "{{ cluster["hooks"]["cloudProvider"] }}"
-{% endif %}
-{% if cluster["hooks"].get("cloudProviderConfig") %}
-  cloud-config: "/etc/kubernetes/cloud-config.json"
-controllerManagerExtraVolumes:
-- name: cloud
-  hostPath: "/etc/kubernetes/cloud-config.json"
-  mountPath: "/etc/kubernetes/cloud-config.json"
-{% endif %}
-schedulerExtraArgs:
-  # required if we want prometheus to be able to scrape (default: 127.0.0.1)
-  address: 0.0.0.0
-EOL
-
+sudo tee ~/kubeadm-config-master.yaml > /dev/null <<EOF
+{% include "fragments/kubeadm-config-master.yaml.j2" %}
+EOF
 if curl -f http://localhost:10255/healthz > /dev/null; then
     log INFO "kubelet already running, skipping kubeadm init ..."
 else
     log INFO "running kubeadm init ..."
-    sudo kubeadm init --config=kubeadm-config.yaml
+    sudo kubeadm init --config=kubeadm-config-master.yaml 2>&1 | tee ~/kubeadm.log
+    exitcode="${PIPESTATUS[0]}"
+    if [ "${exitcode}" != 0 ]; then
+	log ERROR "kubeadm join failed with exitcode ${exitcode} ..."
+	exit ${exitcode}
+    fi
 fi
 
 # kubadm marks the node a master by setting the appropriate label
@@ -289,6 +209,10 @@ sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
 sudo chown $(id -u):$(id -g) $HOME/.kube/config
 
 # scale kube-dns to the number of masters running
+log INFO "awaiting coredns deployment ..."
+until kubectl get deployment -n kube-system coredns > /dev/null; do
+    sleep 2s
+done
 log INFO "scaling coredns deployment ..."
 kubectl scale --replicas={{ cluster["masters"]  | length }} -n kube-system deployment/coredns
 
@@ -310,8 +234,8 @@ kubectl apply -f ~/weave.yaml
 if ! kubectl get clusterrolebinding serviceaccounts-cluster-admin > /dev/null; then
     log INFO "enabling permissive mode: all service accounts bound to role cluster-admin ..."
     kubectl create clusterrolebinding serviceaccounts-cluster-admin \
-	    --clusterrole=cluster-admin \
-	    --group=system:serviceaccounts
+            --clusterrole=cluster-admin \
+            --group=system:serviceaccounts
 fi
 
 {% endif %}
diff --git a/hakubeinstaller/templates/worker.sh.j2 b/hakubeinstaller/templates/worker.sh.j2
--- a/hakubeinstaller/templates/worker.sh.j2
+++ b/hakubeinstaller/templates/worker.sh.j2
@@ -28,22 +28,20 @@ sudo chmod 600 $HOME/.ssh/id_rsa
 #
 # Run kubeadm
 #
-cat > kubeadm-config.yaml <<EOL
-apiVersion: kubeadm.k8s.io/v1alpha1
-kind: NodeConfiguration
-nodeName: {{ worker_name }}
-token: {{ cluster_token }}
-discoveryTokenUnsafeSkipCAVerification: true
-discoveryTokenAPIServers:
-- {{ cluster["masterLoadBalancerAddress"] }}:6443
-EOL
-
+sudo tee ~/kubeadm-config-worker.yaml > /dev/null <<EOF
+{% include "fragments/kubeadm-config-worker.yaml.j2" %}
+EOF
 if curl -f http://localhost:10255/healthz > /dev/null; then
     log INFO "kubelet already running, skipping kubeadm join ..."
 else
     log INFO "running kubeadm join ..."
-	# will wait (indefinitely) for a master to become available
-    sudo kubeadm join --config=kubeadm-config.yaml
+    # will wait (indefinitely) for a master to become available
+    sudo kubeadm join --config=kubeadm-config-worker.yaml 2>&1 | tee ~/kubeadm.log
+    exitcode="${PIPESTATUS[0]}"
+    if [ "${exitcode}" != 0 ]; then
+	log ERROR "kubeadm join failed with exitcode ${exitcode} ..."
+	exit ${exitcode}
+    fi
 fi
 
 log INFO "bootscript completed."
